SELECT SYSDATE FROM DUAL;

SELECT SYSTIMESTAMP FROM DUAL;

SELECT 2*2 FROM DUAL;

SELECT ABS(-15) FROM DUAL;

SELECT SQRT(5) FROM DUAL;

SELECT ROUND(15.19,1) FROM DUAL;

SELECT LOWER('IVAN BAYROSS') AS LC FROM DUAL;

SELECT UPPER('ivan bayross') AS UC FROM DUAL;

SELECT ADD_MONTHS(SYSDATE,5) FROM DUAL;

SELECT MONTHS_BETWEEN(TO_DATE('02-07-01','DD-MM-YY'),TO_DATE('02-JAN-01','DD-MM-YY')) AS MONTHS FROM DUAL;

SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY') AS ND FROM DUAL;
