CREATE TABLE EMP_CS2_47(
	EMPNO number(4) PRIMARY KEY,
	ENAME varchar(30) NOT NULL,
	JOB char(20),
	MGR number(4),
	HIREDATE date,
	SAL number(4),
	COMM number(4),
	DEPTNO number(2));


CREATE TABLE DEPT_CS2_47(
	DEPTNO number(2) PRIMARY KEY,
	DNAME varchar(15) NOT NULL,
	LOD varchar(15) NOT NULL);

DESC DEPT_CS2_47;

DESC EMP_CS2_47;

INSERT INTO EMP_CS2_47 VALUES(&eno,'&ename','&job',&mgr,TO_DATE	('&hd','DD/MM/YY'),&sal,&com,&dno);

INSERT INTO DEPT_CS2_47 VALUES(&deptno,'&dname','&loc');

SELECT * FROM EMP_CS2_47;

SELECT * FROM EMP_CS2_47 WHERE JOB = 'Manager';

SELECT * FROM EMP_CS2_47 WHERE EMPNO=7369;

SELECT * FROM EMP_CS2_47 WHERE HIREDATE = TO_DATE('01-MAY-1981','DD-MON-YYYY');

SELECT * FROM EMP_CS2_47 WHERE SAL>1500;

SELECT * FROM EMP_CS2_47 WHERE COMM IS NULL;

ALTER TABLE EMP_CS2_47 ADD Phone_No number(10);

ALTER TABLE EMP_CS2_47 MODIFY JOB VARCHAR2(20);

ALTER TABLE EMP_CS2_47 DROP COLUMN Phone_No;
