CREATE TABLE GRADE47
(
GRADE VARCHAR(10),
MINSAL NUMBER(6),
MAXSAL NUMBER(6)
);

SELECT ENAME, SAL
FROM EMP47
WHERE SAL = (SELECT MAX(SAL) FROM EMP47);

SELECT ENAME, SAL
FROM EMP47
WHERE JOB = 'SALESMAN' 
AND 
SAL = (SELECT MIN(SAL) FROM EMP47);

SELECT ENAME, SAL
FROM EMP47
WHERE JOB = 'SALESMAN'
AND SAL = (SELECT MIN(SAL) FROM EMP47 WHERE JOB = 'SALESMAN');

SELECT DEPT_NAME
FROM (
    SELECT DEPT_NAME, AVG(SAL) AS AVG_SAL
    FROM EMP47
    GROUP BY DEPT_NAME
    ORDER BY AVG_SAL DESC
)
WHERE ROWNUM = 1;

SELECT ENAME
FROM EMP47
WHERE SAL > (SELECT SAL FROM EMP47 WHERE ENAME = 'MNO');

SELECT ENAME,HIREDATE
FROM EMP47
WHERE HIREDATE > (
    SELECT HIREDATE
    FROM EMP47
    WHERE ENAME = 'ABC'
);

SELECT DEPT_NAME FROM EMP47
WHERE ENAME = 'GHI';

SELECT DEPT_NAME
FROM (
    SELECT DEPT_NAME, SUM(SAL) AS TOTAL_SAL
    FROM EMP47
    GROUP BY DEPT_NAME
    ORDER BY TOTAL_SAL DESC
)
WHERE ROWNUM = 1;

